CREATE TABLE Users (
  Id INT IDENTITY(1,1) PRIMARY KEY,
  Email NVARCHAR(200) UNIQUE NOT NULL,
  Name NVARCHAR(200),
  Role NVARCHAR(50)
);

CREATE TABLE Targets (
  Id INT IDENTITY(1,1) PRIMARY KEY,
  UserId INT NOT NULL FOREIGN KEY REFERENCES Users(Id),
  Month NVARCHAR(7) NOT NULL,
  RevenueTarget DECIMAL(18,2),
  DepositTarget DECIMAL(18,2),
  UNIQUE(UserId, Month)
);
